// ===== HIRAGANA =====
const HIRAGANA = [
  { char:'あ', romaji:'a',   group:'Vowel',   words:[{w:'あめ',r:'ame',m:'rain'},{w:'あお',r:'ao',m:'blue'},{w:'あさ',r:'asa',m:'morning'}] },
  { char:'い', romaji:'i',   group:'Vowel',   words:[{w:'いぬ',r:'inu',m:'dog'},{w:'いえ',r:'ie',m:'house'},{w:'いと',r:'ito',m:'thread'}] },
  { char:'う', romaji:'u',   group:'Vowel',   words:[{w:'うみ',r:'umi',m:'sea'},{w:'うた',r:'uta',m:'song'},{w:'うし',r:'ushi',m:'cow'}] },
  { char:'え', romaji:'e',   group:'Vowel',   words:[{w:'えき',r:'eki',m:'station'},{w:'えん',r:'en',m:'yen'},{w:'えほん',r:'ehon',m:'picture book'}] },
  { char:'お', romaji:'o',   group:'Vowel',   words:[{w:'おか',r:'oka',m:'hill'},{w:'おに',r:'oni',m:'demon'},{w:'おと',r:'oto',m:'sound'}] },
  { char:'か', romaji:'ka',  group:'K-row',   words:[{w:'かさ',r:'kasa',m:'umbrella'},{w:'かわ',r:'kawa',m:'river'},{w:'かに',r:'kani',m:'crab'}] },
  { char:'き', romaji:'ki',  group:'K-row',   words:[{w:'きつね',r:'kitsune',m:'fox'},{w:'きく',r:'kiku',m:'chrysanthemum'},{w:'きもの',r:'kimono',m:'kimono'}] },
  { char:'く', romaji:'ku',  group:'K-row',   words:[{w:'くも',r:'kumo',m:'cloud'},{w:'くち',r:'kuchi',m:'mouth'},{w:'くつ',r:'kutsu',m:'shoes'}] },
  { char:'け', romaji:'ke',  group:'K-row',   words:[{w:'けむり',r:'kemuri',m:'smoke'},{w:'けいと',r:'keito',m:'wool'},{w:'けが',r:'kega',m:'injury'}] },
  { char:'こ', romaji:'ko',  group:'K-row',   words:[{w:'こえ',r:'koe',m:'voice'},{w:'こい',r:'koi',m:'carp'},{w:'こころ',r:'kokoro',m:'heart'}] },
  { char:'さ', romaji:'sa',  group:'S-row',   words:[{w:'さくら',r:'sakura',m:'cherry blossom'},{w:'さかな',r:'sakana',m:'fish'},{w:'さむい',r:'samui',m:'cold'}] },
  { char:'し', romaji:'shi', group:'S-row',   words:[{w:'しろ',r:'shiro',m:'white/castle'},{w:'しお',r:'shio',m:'salt'},{w:'しずか',r:'shizuka',m:'quiet'}] },
  { char:'す', romaji:'su',  group:'S-row',   words:[{w:'すし',r:'sushi',m:'sushi'},{w:'すな',r:'suna',m:'sand'},{w:'すき',r:'suki',m:'like'}] },
  { char:'せ', romaji:'se',  group:'S-row',   words:[{w:'せかい',r:'sekai',m:'world'},{w:'せんせい',r:'sensei',m:'teacher'},{w:'せみ',r:'semi',m:'cicada'}] },
  { char:'そ', romaji:'so',  group:'S-row',   words:[{w:'そら',r:'sora',m:'sky'},{w:'そば',r:'soba',m:'soba noodles'},{w:'そと',r:'soto',m:'outside'}] },
  { char:'た', romaji:'ta',  group:'T-row',   words:[{w:'たこ',r:'tako',m:'octopus'},{w:'たき',r:'taki',m:'waterfall'},{w:'たまご',r:'tamago',m:'egg'}] },
  { char:'ち', romaji:'chi', group:'T-row',   words:[{w:'ちず',r:'chizu',m:'map'},{w:'ちから',r:'chikara',m:'strength'},{w:'ちょう',r:'chou',m:'butterfly'}] },
  { char:'つ', romaji:'tsu', group:'T-row',   words:[{w:'つき',r:'tsuki',m:'moon'},{w:'つる',r:'tsuru',m:'crane'},{w:'つゆ',r:'tsuyu',m:'rainy season'}] },
  { char:'て', romaji:'te',  group:'T-row',   words:[{w:'てがみ',r:'tegami',m:'letter'},{w:'てら',r:'tera',m:'temple'},{w:'てんき',r:'tenki',m:'weather'}] },
  { char:'と', romaji:'to',  group:'T-row',   words:[{w:'とり',r:'tori',m:'bird'},{w:'とけい',r:'tokei',m:'clock'},{w:'ともだち',r:'tomodachi',m:'friend'}] },
  { char:'な', romaji:'na',  group:'N-row',   words:[{w:'なみ',r:'nami',m:'wave'},{w:'なつ',r:'natsu',m:'summer'},{w:'なまえ',r:'namae',m:'name'}] },
  { char:'に', romaji:'ni',  group:'N-row',   words:[{w:'にじ',r:'niji',m:'rainbow'},{w:'にわ',r:'niwa',m:'garden'},{w:'にほん',r:'nihon',m:'Japan'}] },
  { char:'ぬ', romaji:'nu',  group:'N-row',   words:[{w:'ぬの',r:'nuno',m:'cloth'},{w:'ぬま',r:'numa',m:'swamp'},{w:'ぬいぐるみ',r:'nuigurumi',m:'stuffed toy'}] },
  { char:'ね', romaji:'ne',  group:'N-row',   words:[{w:'ねこ',r:'neko',m:'cat'},{w:'ねむい',r:'nemui',m:'sleepy'},{w:'ねつ',r:'netsu',m:'fever'}] },
  { char:'の', romaji:'no',  group:'N-row',   words:[{w:'のり',r:'nori',m:'seaweed'},{w:'のはら',r:'nohara',m:'field'},{w:'のみもの',r:'nomimono',m:'drink'}] },
  { char:'は', romaji:'ha',  group:'H-row',   words:[{w:'はな',r:'hana',m:'flower'},{w:'はる',r:'haru',m:'spring'},{w:'はし',r:'hashi',m:'chopsticks'}] },
  { char:'ひ', romaji:'hi',  group:'H-row',   words:[{w:'ひと',r:'hito',m:'person'},{w:'ひかり',r:'hikari',m:'light'},{w:'ひまわり',r:'himawari',m:'sunflower'}] },
  { char:'ふ', romaji:'fu',  group:'H-row',   words:[{w:'ふゆ',r:'fuyu',m:'winter'},{w:'ふね',r:'fune',m:'boat'},{w:'ふじ',r:'fuji',m:'Mt. Fuji'}] },
  { char:'へ', romaji:'he',  group:'H-row',   words:[{w:'へや',r:'heya',m:'room'},{w:'へび',r:'hebi',m:'snake'},{w:'へいわ',r:'heiwa',m:'peace'}] },
  { char:'ほ', romaji:'ho',  group:'H-row',   words:[{w:'ほし',r:'hoshi',m:'star'},{w:'ほん',r:'hon',m:'book'},{w:'ほたる',r:'hotaru',m:'firefly'}] },
  { char:'ま', romaji:'ma',  group:'M-row',   words:[{w:'まど',r:'mado',m:'window'},{w:'まつり',r:'matsuri',m:'festival'},{w:'まち',r:'machi',m:'town'}] },
  { char:'み', romaji:'mi',  group:'M-row',   words:[{w:'みず',r:'mizu',m:'water'},{w:'みち',r:'michi',m:'road'},{w:'みかん',r:'mikan',m:'mandarin'}] },
  { char:'む', romaji:'mu',  group:'M-row',   words:[{w:'むし',r:'mushi',m:'insect'},{w:'むら',r:'mura',m:'village'},{w:'むすめ',r:'musume',m:'daughter'}] },
  { char:'め', romaji:'me',  group:'M-row',   words:[{w:'めだか',r:'medaka',m:'killifish'},{w:'めがね',r:'megane',m:'glasses'},{w:'めぐみ',r:'megumi',m:'blessing'}] },
  { char:'も', romaji:'mo',  group:'M-row',   words:[{w:'もり',r:'mori',m:'forest'},{w:'もも',r:'momo',m:'peach'},{w:'もち',r:'mochi',m:'rice cake'}] },
  { char:'や', romaji:'ya',  group:'Y-row',   words:[{w:'やま',r:'yama',m:'mountain'},{w:'やさい',r:'yasai',m:'vegetable'},{w:'やきとり',r:'yakitori',m:'grilled chicken'}] },
  { char:'ゆ', romaji:'yu',  group:'Y-row',   words:[{w:'ゆき',r:'yuki',m:'snow'},{w:'ゆめ',r:'yume',m:'dream'},{w:'ゆびわ',r:'yubiwa',m:'ring'}] },
  { char:'よ', romaji:'yo',  group:'Y-row',   words:[{w:'よる',r:'yoru',m:'night'},{w:'よみ',r:'yomi',m:'reading'},{w:'ようかい',r:'youkai',m:'spirit'}] },
  { char:'ら', romaji:'ra',  group:'R-row',   words:[{w:'らくだ',r:'rakuda',m:'camel'},{w:'らいねん',r:'rainen',m:'next year'},{w:'らんぷ',r:'ranpu',m:'lamp'}] },
  { char:'り', romaji:'ri',  group:'R-row',   words:[{w:'りんご',r:'ringo',m:'apple'},{w:'りゅう',r:'ryuu',m:'dragon'},{w:'りす',r:'risu',m:'squirrel'}] },
  { char:'る', romaji:'ru',  group:'R-row',   words:[{w:'るびー',r:'rubii',m:'ruby'},{w:'るすばん',r:'rusuban',m:'house-sitting'},{w:'るーぷ',r:'ruupu',m:'loop'}] },
  { char:'れ', romaji:'re',  group:'R-row',   words:[{w:'れんこん',r:'renkon',m:'lotus root'},{w:'れいぞうこ',r:'reizouko',m:'fridge'},{w:'れきし',r:'rekishi',m:'history'}] },
  { char:'ろ', romaji:'ro',  group:'R-row',   words:[{w:'ろうそく',r:'rousoku',m:'candle'},{w:'ろば',r:'roba',m:'donkey'},{w:'ろっく',r:'rokku',m:'rock music'}] },
  { char:'わ', romaji:'wa',  group:'W-row',   words:[{w:'わに',r:'wani',m:'crocodile'},{w:'わた',r:'wata',m:'cotton'},{w:'わかば',r:'wakaba',m:'young leaves'}] },
  { char:'を', romaji:'wo',  group:'W-row',   words:[{w:'(object marker)',r:'wo',m:'particle を'}] },
  { char:'ん', romaji:'n',   group:'N-nasal', words:[{w:'(nasal sound)',r:'n',m:'used at end of syllables'}] },
];

// ===== KATAKANA =====
const KATAKANA = [
  { char:'ア', romaji:'a',   group:'Vowel',   words:[{w:'アイス',r:'aisu',m:'ice cream'},{w:'アニメ',r:'anime',m:'anime'},{w:'アジア',r:'ajia',m:'Asia'}] },
  { char:'イ', romaji:'i',   group:'Vowel',   words:[{w:'イチゴ',r:'ichigo',m:'strawberry'},{w:'イルカ',r:'iruka',m:'dolphin'},{w:'インク',r:'inku',m:'ink'}] },
  { char:'ウ', romaji:'u',   group:'Vowel',   words:[{w:'ウサギ',r:'usagi',m:'rabbit'},{w:'ウイルス',r:'uirusu',m:'virus'},{w:'ウール',r:'uuru',m:'wool'}] },
  { char:'エ', romaji:'e',   group:'Vowel',   words:[{w:'エビ',r:'ebi',m:'shrimp'},{w:'エコ',r:'eko',m:'eco'},{w:'エンジン',r:'enjin',m:'engine'}] },
  { char:'オ', romaji:'o',   group:'Vowel',   words:[{w:'オレンジ',r:'orenji',m:'orange'},{w:'オオカミ',r:'ookami',m:'wolf'},{w:'オーブン',r:'oobun',m:'oven'}] },
  { char:'カ', romaji:'ka',  group:'K-row',   words:[{w:'カメラ',r:'kamera',m:'camera'},{w:'カフェ',r:'kafe',m:'café'},{w:'カレー',r:'karee',m:'curry'}] },
  { char:'キ', romaji:'ki',  group:'K-row',   words:[{w:'キツネ',r:'kitsune',m:'fox'},{w:'キャット',r:'kyatto',m:'cat'},{w:'キウイ',r:'kiui',m:'kiwi'}] },
  { char:'ク', romaji:'ku',  group:'K-row',   words:[{w:'クマ',r:'kuma',m:'bear'},{w:'クッキー',r:'kukkii',m:'cookie'},{w:'クラス',r:'kurasu',m:'class'}] },
  { char:'ケ', romaji:'ke',  group:'K-row',   words:[{w:'ケーキ',r:'keeki',m:'cake'},{w:'ケトル',r:'ketoru',m:'kettle'},{w:'ケガ',r:'kega',m:'injury'}] },
  { char:'コ', romaji:'ko',  group:'K-row',   words:[{w:'コーヒー',r:'koohii',m:'coffee'},{w:'コアラ',r:'koara',m:'koala'},{w:'コート',r:'kooto',m:'coat'}] },
  { char:'サ', romaji:'sa',  group:'S-row',   words:[{w:'サクラ',r:'sakura',m:'cherry blossom'},{w:'サラダ',r:'sarada',m:'salad'},{w:'サンタ',r:'santa',m:'Santa'}] },
  { char:'シ', romaji:'shi', group:'S-row',   words:[{w:'シロクマ',r:'shirokuma',m:'polar bear'},{w:'シャツ',r:'shatsu',m:'shirt'},{w:'シール',r:'shiiru',m:'sticker'}] },
  { char:'ス', romaji:'su',  group:'S-row',   words:[{w:'スシ',r:'sushi',m:'sushi'},{w:'スカート',r:'sukaato',m:'skirt'},{w:'スター',r:'sutaa',m:'star'}] },
  { char:'セ', romaji:'se',  group:'S-row',   words:[{w:'セーター',r:'seetaa',m:'sweater'},{w:'センス',r:'sensu',m:'sense'},{w:'セロリ',r:'serori',m:'celery'}] },
  { char:'ソ', romaji:'so',  group:'S-row',   words:[{w:'ソファ',r:'sofa',m:'sofa'},{w:'ソース',r:'soosu',m:'sauce'},{w:'ソング',r:'songu',m:'song'}] },
  { char:'タ', romaji:'ta',  group:'T-row',   words:[{w:'タコ',r:'tako',m:'octopus'},{w:'タオル',r:'taoru',m:'towel'},{w:'タピオカ',r:'tapioka',m:'tapioca'}] },
  { char:'チ', romaji:'chi', group:'T-row',   words:[{w:'チョコ',r:'choko',m:'chocolate'},{w:'チーズ',r:'chiizu',m:'cheese'},{w:'チューリップ',r:'chuurippu',m:'tulip'}] },
  { char:'ツ', romaji:'tsu', group:'T-row',   words:[{w:'ツナ',r:'tsuna',m:'tuna'},{w:'ツアー',r:'tsuaa',m:'tour'},{w:'ツリー',r:'tsurii',m:'tree'}] },
  { char:'テ', romaji:'te',  group:'T-row',   words:[{w:'テスト',r:'tesuto',m:'test'},{w:'テーブル',r:'teburu',m:'table'},{w:'テニス',r:'tenisu',m:'tennis'}] },
  { char:'ト', romaji:'to',  group:'T-row',   words:[{w:'トマト',r:'tomato',m:'tomato'},{w:'トースト',r:'toosuto',m:'toast'},{w:'トナカイ',r:'tonakai',m:'reindeer'}] },
  { char:'ナ', romaji:'na',  group:'N-row',   words:[{w:'ナイフ',r:'naifu',m:'knife'},{w:'ナッツ',r:'nattsu',m:'nuts'},{w:'ナース',r:'naaasu',m:'nurse'}] },
  { char:'ニ', romaji:'ni',  group:'N-row',   words:[{w:'ニンジン',r:'ninjin',m:'carrot'},{w:'ニュース',r:'nyuusu',m:'news'},{w:'ニット',r:'nitto',m:'knit'}] },
  { char:'ヌ', romaji:'nu',  group:'N-row',   words:[{w:'ヌードル',r:'nuudoru',m:'noodle'},{w:'ヌガー',r:'nugaa',m:'nougat'}] },
  { char:'ネ', romaji:'ne',  group:'N-row',   words:[{w:'ネコ',r:'neko',m:'cat'},{w:'ネクタイ',r:'nekutai',m:'necktie'},{w:'ネット',r:'netto',m:'net/internet'}] },
  { char:'ノ', romaji:'no',  group:'N-row',   words:[{w:'ノート',r:'nooto',m:'notebook'},{w:'ノイズ',r:'noizu',m:'noise'},{w:'ノック',r:'nokku',m:'knock'}] },
  { char:'ハ', romaji:'ha',  group:'H-row',   words:[{w:'ハート',r:'haato',m:'heart'},{w:'ハナ',r:'hana',m:'flower'},{w:'ハム',r:'hamu',m:'ham'}] },
  { char:'ヒ', romaji:'hi',  group:'H-row',   words:[{w:'ヒーロー',r:'hiiroo',m:'hero'},{w:'ヒマワリ',r:'himawari',m:'sunflower'},{w:'ヒント',r:'hinto',m:'hint'}] },
  { char:'フ', romaji:'fu',  group:'H-row',   words:[{w:'フルーツ',r:'furuutsu',m:'fruit'},{w:'フラワー',r:'furawaa',m:'flower'},{w:'フォーク',r:'fooku',m:'fork'}] },
  { char:'ヘ', romaji:'he',  group:'H-row',   words:[{w:'ヘア',r:'hea',m:'hair'},{w:'ヘルメット',r:'herumetto',m:'helmet'},{w:'ヘビ',r:'hebi',m:'snake'}] },
  { char:'ホ', romaji:'ho',  group:'H-row',   words:[{w:'ホテル',r:'hoteru',m:'hotel'},{w:'ホット',r:'hotto',m:'hot'},{w:'ホタル',r:'hotaru',m:'firefly'}] },
  { char:'マ', romaji:'ma',  group:'M-row',   words:[{w:'マンゴー',r:'mangoo',m:'mango'},{w:'マスク',r:'masuku',m:'mask'},{w:'マカロン',r:'makaron',m:'macaron'}] },
  { char:'ミ', romaji:'mi',  group:'M-row',   words:[{w:'ミルク',r:'miruku',m:'milk'},{w:'ミント',r:'minto',m:'mint'},{w:'ミラー',r:'miraa',m:'mirror'}] },
  { char:'ム', romaji:'mu',  group:'M-row',   words:[{w:'ムース',r:'muusu',m:'mousse'},{w:'ムービー',r:'muubii',m:'movie'},{w:'ムード',r:'muudo',m:'mood'}] },
  { char:'メ', romaji:'me',  group:'M-row',   words:[{w:'メロン',r:'meron',m:'melon'},{w:'メール',r:'meeru',m:'email'},{w:'メモ',r:'memo',m:'memo'}] },
  { char:'モ', romaji:'mo',  group:'M-row',   words:[{w:'モデル',r:'moderu',m:'model'},{w:'モンスター',r:'monsutaa',m:'monster'},{w:'モカ',r:'moka',m:'mocha'}] },
  { char:'ヤ', romaji:'ya',  group:'Y-row',   words:[{w:'ヤシ',r:'yashi',m:'palm tree'},{w:'ヤクルト',r:'yakuruto',m:'Yakult'},{w:'ヤード',r:'yaado',m:'yard'}] },
  { char:'ユ', romaji:'yu',  group:'Y-row',   words:[{w:'ユニコーン',r:'yunikoon',m:'unicorn'},{w:'ユーモア',r:'yuumoa',m:'humor'},{w:'ユリ',r:'yuri',m:'lily'}] },
  { char:'ヨ', romaji:'yo',  group:'Y-row',   words:[{w:'ヨーグルト',r:'yooguruto',m:'yogurt'},{w:'ヨット',r:'yotto',m:'yacht'},{w:'ヨガ',r:'yoga',m:'yoga'}] },
  { char:'ラ', romaji:'ra',  group:'R-row',   words:[{w:'ラーメン',r:'raamen',m:'ramen'},{w:'ラジオ',r:'rajio',m:'radio'},{w:'ラベンダー',r:'rabendaa',m:'lavender'}] },
  { char:'リ', romaji:'ri',  group:'R-row',   words:[{w:'リンゴ',r:'ringo',m:'apple'},{w:'リボン',r:'ribon',m:'ribbon'},{w:'リス',r:'risu',m:'squirrel'}] },
  { char:'ル', romaji:'ru',  group:'R-row',   words:[{w:'ルビー',r:'rubii',m:'ruby'},{w:'ルーム',r:'ruumu',m:'room'},{w:'ルール',r:'ruuru',m:'rule'}] },
  { char:'レ', romaji:'re',  group:'R-row',   words:[{w:'レモン',r:'remon',m:'lemon'},{w:'レース',r:'reesu',m:'lace/race'},{w:'レストラン',r:'resutoran',m:'restaurant'}] },
  { char:'ロ', romaji:'ro',  group:'R-row',   words:[{w:'ロボット',r:'robotto',m:'robot'},{w:'ロール',r:'rooru',m:'roll'},{w:'ロマンス',r:'romansu',m:'romance'}] },
  { char:'ワ', romaji:'wa',  group:'W-row',   words:[{w:'ワイン',r:'wain',m:'wine'},{w:'ワニ',r:'wani',m:'crocodile'},{w:'ワッフル',r:'waffuru',m:'waffle'}] },
  { char:'ヲ', romaji:'wo',  group:'W-row',   words:[{w:'(object marker)',r:'wo',m:'particle ヲ'}] },
  { char:'ン', romaji:'n',   group:'N-nasal', words:[{w:'(nasal sound)',r:'n',m:'used at end of syllables'}] },
];
